version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexaops_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nexaops
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexaops_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nexaops_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
